### ISSUE TITLE
Build libraries for openSSL/TLS

### ISSUE THREAD

**Issue by jurjen-van-dijk** [baresip/baresip-ios#24]
I try to use baresip in an iOS app, but need to connect with TLS. However, the lib's build with this makefile are excluding openSSL and TLS. Why is that, and how can I build lib's that use TLS?

**Comment by alfredh** [comment]
you need to add a makefile target to cross-compile openssl.

see here for a similar project:

https://github.com/alfredh/baresip-android/blob/master/Makefile#L202

a Pull Request is welcome.

**Comment by rrpathak007** [comment]
I have added openssl and bitcode bellow repo.
https://github.com/rrpathak007/baresip-ios-bitcode

Pre Build openssl for ios.
https://github.com/rrpathak007/ios-openssl-lib

@jurjen-van-dijk  Hope this will help you. 
@alfredh I already submit a Pull Request for bitcode. let me know if you want me to add openssl on it.

**Comment by jurjen-van-dijk** [comment]
Thanks @rtcexpert ! I will have a look at it.

**Comment by alfredh** [comment]
please make a PR to cross-compile OpenSSL for iOS.
