### ISSUE TITLE
Install baresip 1.0.0 getting error of No rule to make target

### ISSUE THREAD

**Issue by samirmagnates** [baresip/baresip-ios#34]
I am trying to install updated baresip version 1.0.0, before that I alreday installed 0.6.5 and its successfuly installd:  Now I get 4  zip from below link (master)

https://github.com/creytiv/rem
https://github.com/baresip/re
https://github.com/baresip/baresip
and 
https://github.com/baresip/baresip-ios

added three unzip folder rem, re and baresip in baresip-ios-master

then fire command : 
`$ make contrib`

its giving error at time of creating folder x86_64

`  
CC      /Users/samir/Downloads/Baresip1.0.0/baresip-ios-master/build/x86_64/librem/h264/nal.o
  CC      /Users/samir/Downloads/Baresip1.0.0/baresip-ios-master/build/x86_64/librem/h264/sps.o
  LD      librem.dylib
  AR      librem.a
Makefile:134: modules/opengles/module.mk: No such file or directory
make[1]: *** No rule to make target modules/opengles/module.mk.  Stop.
make: *** [baresip] Error 2
`

I think its an issue of https://github.com/baresip/baresip-ios which is not updated as per baresip verison 1.0.0

**Comment by alfredh** [comment]
can you please try again with latest HEAD from git ?

I made a fix in 61f79e69e741e017156c54a97d4d793355d1ffd2

NOTE: this project needs a maintainer, I am not using it actively anymore.

**Comment by samirmagnates** [comment]
@alfredh Thanks for your support... Now it's working perfectly.
 I am really interested to maintain this project.. what should I do for the same? is there any guideline to maintain this project?

**Comment by Koshub** [comment]
@alfredh I have already fixed this and other issues in [this PR](https://github.com/baresip/baresip-ios/pull/32), please take a look at commit commets. It will definitely help other developers to get started using baresip on iOS

**Comment by alfredh** [comment]
all pull requests are welcome :)

We need some help to maintain this project. Please let me know if you can help :)

**Comment by Koshub** [comment]
According to the license, this project is almost the single solution for SIP stack on iOS which is compatible with App Store without any legal issues (see [here](https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement)  for more details). So it worth supporting it. The other good solutions are either paid or LGPL, GPL licensed.
