### ISSUE TITLE
Can't compile g722 codec

### ISSUE THREAD

**Issue by HammerProgrammer** [baresip/baresip-ios#36]
`modules/g722/g722.c:13:10: fatal error: 'spandsp.h' file not found`
I've installed spandsp with Homebrew like it says in the wiki but it still can't find the header
managed to fix this by adding a CPATH to /usr/local/include
but now during building in Xcode I get this error

`Undefined symbols for architecture x86_64:
  "_g722_decode", referenced from:
      _decode in libbaresip.a(g722.o)
  "_g722_decode_init", referenced from:
      _decode_update in libbaresip.a(g722.o)
  "_g722_encode", referenced from:
      _encode in libbaresip.a(g722.o)
  "_g722_encode_init", referenced from:
      _encode_update in libbaresip.a(g722.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by lilkid3** [comment]
Hi @HammerProgrammer, I have the same issue using, how did you handle the g722 codec. Thanks

**Comment by HammerProgrammer** [comment]
> 
> 
> Hi @HammerProgrammer, I have the same issue using, how did you handle the g722 codec. Thanks

The g722 codec is not included in baresip you need to compile it yourself

**Comment by lilkid3** [comment]
@HammerProgrammer Thanks, could you please share steps on how to compile the G722 codec. Thanks
